// functions/src/triggers/generateRecurringExpenses.ts
// Daily scheduler — materializes due recurring-expense templates into
// real expense docs (rent, subscriptions — roommate mode).
//
// IDEMPOTENCY: expense ids are deterministic (rec_{templateId}_{date}) and
// written with create() — retries and overlapping runs never double-charge.
// CATCH-UP: templates whose nextRunDate fell behind (scheduler downtime)
// generate every missed occurrence, one per loop iteration.

import * as admin from 'firebase-admin'
import { onSchedule } from 'firebase-functions/v2/scheduler'
import {
  computeNextRunDate,
  isDue,
  isExpired,
  occurrenceExpenseId,
  toDateString,
  type RecurrenceFrequency,
} from '../engine/recurrence'

interface RecurringExpenseDoc {
  id: string
  groupId: string
  description: string
  amount: number
  currency: string
  category: string
  paidBy: string
  splitType: string
  splits: Record<string, number>
  frequency: RecurrenceFrequency
  dayOfMonth?: number
  nextRunDate: string
  endDate?: string
  active: boolean
  createdBy: string
}

const MAX_CATCHUP_OCCURRENCES = 12 // safety valve against runaway templates

export const generateRecurringExpenses = onSchedule(
  {
    schedule: 'every day 00:30',
    timeZone: 'Asia/Kolkata',
    region: 'asia-south1',
    memory: '256MiB',
    timeoutSeconds: 300,
  },
  async () => {
    const db = admin.firestore()
    // Job runs 00:30 IST — that's still the previous day in UTC, so
    // "today" must be derived in IST (UTC+5:30) or every run lags a day.
    const IST_OFFSET_MS = 5.5 * 60 * 60 * 1000
    const today = toDateString(new Date(Date.now() + IST_OFFSET_MS))

    const dueSnap = await db
      .collectionGroup('recurringExpenses')
      .where('active', '==', true)
      .where('nextRunDate', '<=', today)
      .get()

    console.info(`[apna] generateRecurringExpenses: ${dueSnap.size} due templates (${today})`)

    for (const templateDoc of dueSnap.docs) {
      const template = { ...(templateDoc.data() as RecurringExpenseDoc), id: templateDoc.id }
      const groupId = template.groupId

      try {
        let runDate = template.nextRunDate
        let generated = 0

        while (
          isDue({ ...template, nextRunDate: runDate }, today) &&
          generated < MAX_CATCHUP_OCCURRENCES
        ) {
          const expenseId = occurrenceExpenseId(template.id, runDate)
          const expenseRef = db.doc(`groups/${groupId}/expenses/${expenseId}`)

          try {
            // create() fails if the doc exists — the idempotency guarantee
            await expenseRef.create({
              id: expenseId,
              groupId,
              description: template.description,
              amount: template.amount,
              currency: template.currency ?? 'INR',
              category: template.category,
              paidBy: template.paidBy,
              splitType: template.splitType,
              splits: template.splits,
              date: runDate,
              createdBy: template.createdBy,
              createdAt: admin.firestore.FieldValue.serverTimestamp(),
              isSettled: false,
              recurringTemplateId: template.id,
            })
            generated++
          } catch (err: unknown) {
            // ALREADY_EXISTS (code 6) — occurrence was generated by a prior run
            if ((err as { code?: number }).code !== 6) throw err
          }

          runDate = computeNextRunDate(runDate, template.frequency, template.dayOfMonth)
        }

        const expired = isExpired({ nextRunDate: runDate, endDate: template.endDate })
        await templateDoc.ref.update({
          nextRunDate: runDate,
          lastGeneratedAt: admin.firestore.FieldValue.serverTimestamp(),
          ...(expired ? { active: false } : {}),
        })

        console.info(
          `[apna] generateRecurringExpenses: template=${template.id} group=${groupId} generated=${generated} next=${runDate}${expired ? ' (expired → deactivated)' : ''}`,
        )
      } catch (err) {
        // One bad template must not block the rest
        console.error(`[apna] generateRecurringExpenses failed template=${template.id} group=${groupId}:`, err)
      }
    }
  },
)
